apiVersion: v1
kind: Service
metadata:
  name: medcare-service
spec:
  type: NodePort
  selector:
    app: eksdemo
  ports:
    - nodePort: 31479 #external traffic
      port: 8081 #port of this service. Cluster members talk via this port
      targetPort: 8080 #where container is actually running